### ISSUE TITLE
Please we want the IOS Version of this Plugin

### ISSUE THREAD

**Issue by Loopex2019** [follow2vivek/StoragePath#1]
Hi . Fist of all thanks for this awesome Plugin . it really helped me a lot . But i saw that you guys said you need a Mac for the IOS Version. That's actually untrue , you don't need that . If you have an ios folder in your Project you can develop for ios too . I am using a Windows Machine and i have that 
folder. But this is gonna be really strange if you don't have one ?

**Comment by follow2vivek** [comment]
I can't test on windows but I got my mac and soon it will be available for ios also.
