### ISSUE TITLE
How to get images from custom path.

### ISSUE THREAD

**Issue by atul-chaudhary** [follow2vivek/StoragePath#4]
I want to retrieve all images in my flutter app from a specific folder/directory in external storage like downloads directory,
please help me.

**Comment by follow2vivek** [comment]
As of now it will return all the folders path, you can filter from that.

**Comment by pishguy** [comment]
@follow2vivek @atul-chaudhary 

i don't understand me how can i do that

`StoragePath` can only  get specific folders 

```
imagesPath
videoPath
audioPath
filePath
```

for example how can i get images inside root folder? or some other folders ?
