### ISSUE TITLE
append list value

### ISSUE THREAD

**Issue by haidar786** [follow2vivek/StoragePath#5]
list value increases when  String paths = await StoragePath.videoPath; called more than once.

**Comment by mohitjadav86** [comment]
same issue here

**Comment by haidar786** [comment]
I'm using this function written in dart for files and folders.
`Future<List<VideoModel>> _getVideosFromStorage() async {
    if (_videoModel == null) {
      List<VideoModel> videoModel = [];
      List<String> directories = [];
      List<FileSystemEntity> files = [];
      Directory directory = Directory('/storage/emulated/0/');
      List<FileSystemEntity> allFiles =
          directory.listSync(recursive: true, followLinks: false);
      allFiles.forEach((file) {
        if (file.path.endsWith('.mp4')) {
          directories.add(file.parent.path);
          files.add(file);
        }
      });
      directories.toSet().toList().forEach((directory) {
        List<Files> videoFiles = [];
        Directory videoDirectory = Directory(directory);
        files = videoDirectory.listSync();
        files.forEach((file) {
          if (file.path.endsWith('.mp4')) {
            videoFiles.add(
              Files(file, null),
            );
          }
        });
        videoModel.add(
          VideoModel(directory.split('/').last, videoFiles),
        );
      });
      _videoModel = videoModel;
    }
    return _videoModel;
  }`

**Comment by haidar786** [comment]
now i'm using [this function and model](https://gist.github.com/haidar786/30395e7c396a2a8bbc13ea3750be4278)

**Comment by follow2vivek** [comment]
fixed.
Update to version 0.2.0.
